# Generated by Django 5.1.3 on 2025-12-23 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Catatan observasi guru', verbose_name='Catatan Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Diagnosis')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diupdate')),
                ('conditions', models.ManyToManyField(blank=True, to='expert.condition', verbose_name='Kondisi Terdeteksi')),
                ('diagnosed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_made', to=settings.AUTH_USER_MODEL, verbose_name='Didiagnosis oleh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='students.student', verbose_name='Siswa')),
                ('symptoms', models.ManyToManyField(to='expert.symptom', verbose_name='Gejala yang Dipilih')),
            ],
            options={
                'verbose_name': 'Hasil Diagnosis',
                'verbose_name_plural': 'Hasil Diagnosis',
                'ordering': ['-created_at'],
            },
        ),
    ]
